owner: alpacax
repo: alpacon-status-dev

sites:
  - name: Alpacon
    url: https://dev.alpacon.io/
  - name: Alpacon API
    url: https://dev.alpacon.io/api/
  - name: Alpacon Docs
    url: https://docs.staging.alpacax.com/
    expectedStatusCodes:
      - 200
      - 403
  - name: Account
    url: https://account.staging.alpacax.com
  - name: Payment
    url: https://pay.staging.alpacax.com/
  - name: Payment API
    url: https://pay.staging.alpacax.com/api/
  - name: AlpacaX
    url: https://staging.alpacax.com/
    expectedStatusCodes:
      - 200
      - 403

status-website:
  publish: true
  cname: status.staging.alpacax.com
  name: ""
  logoUrl: https://raw.githubusercontent.com/alpacax/alpacon-status-dev/master/assets/logo.svg
  favicon: https://raw.githubusercontent.com/alpacax/alpacon-status-dev/master/assets/icon.svg
  faviconSvg: https://raw.githubusercontent.com/alpacax/alpacon-status-dev/master/assets/icon.svg
  customHeadHtml: '<meta name="robots" content="noindex, nofollow">'
  introTitle: "**Alpacon** Dev/Staging Status Monitor"
  introMessage: Real-time status of AlpacaX dev/staging services.
  maxPastIncidents: 10
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
