owner: alpacax
repo: alpacon-status-dev

sites:
  - name: AlpacaX Web
    url: https://staging.alpacax.com/
    expectedStatusCodes:
      - 200
      - 403
  - name: Alpacon Docs
    url: https://docs.staging.alpacax.com/
    expectedStatusCodes:
      - 200
      - 403
  - name: Alpacon Dev
    url: https://dev.alpacon.io/alpacax
  - name: Alpacon Dev API
    url: https://dev.alpacon.io/api/
  - name: Account Service
    url: https://account.staging.alpacax.com
  - name: Payment Web
    url: https://pay.staging.alpacax.com/
  - name: Payment API
    url: https://pay.staging.alpacax.com/api/

status-website:
  publish: true
  baseUrl: /alpacon-status-dev
  name: Alpacon Status (Dev)
  logoUrl: https://raw.githubusercontent.com/alpacax/alpacon-status-dev/master/assets/logo.svg
  favicon: https://raw.githubusercontent.com/alpacax/alpacon-status-dev/master/assets/icon.svg
  faviconSvg: https://raw.githubusercontent.com/alpacax/alpacon-status-dev/master/assets/icon.svg
  introTitle: "**Alpacon** Dev/Staging Status Monitor"
  introMessage: Real-time status of AlpacaX dev/staging services.
  maxPastIncidents: 10
  navbar:
    - title: Status
      href: /alpacon-status-dev
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
