owner: alpacax
repo: alpacon-status-dev

sites:
  - name: AlpacaX Web
    url: https://staging.alpacax.com/
    expectedStatusCodes:
      - 200
      - 403
  - name: Alpacon Docs
    url: https://docs.staging.alpacax.com/
    expectedStatusCodes:
      - 200
      - 403
  - name: Alpacon Dev
    url: https://dev.alpacon.io/alpacax
  - name: Alpacon Dev API
    url: https://dev.alpacon.io/api/
  - name: Account Service
    url: https://account.staging.alpacax.com
  - name: Payment Web
    url: https://pay.staging.alpacax.com/
  - name: Payment API
    url: https://pay.staging.alpacax.com/api/

status-website:
  publish: true
  baseUrl: /
  name: Alpacon Status (Dev)
  introTitle: "**Alpacon** Dev/Staging 환경 상태 모니터링"
  introMessage: AlpacaX dev/staging 서비스의 실시간 상태를 확인할 수 있습니다.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
